### ISSUE TITLE
how to build env locally? 

### ISSUE THREAD

**Issue by 742362144** [utah-scs/splinter#26]
I wanna run splinter in my local cluster, but i meet a lot problem. 
I try to use build.sh in net dir, there are some error while build.

   Compiling zcsi-delay v0.1.0 (/root/splinter/net/test/delay-test)
error: the legacy LLVM-style asm! syntax is no longer supported
  --> test/delay-test/src/nf.rs:7:9
   |
7  |           asm!("nop"
   |           ^---
   |           |
   |  _________help: replace with: `llvm_asm!`
   | |
8  | |              :
9  | |              :
10 | |              :
11 | |              : "volatile");
   | |___________________________^
   |
   = note: consider migrating to the new asm! syntax specified in RFC 2873
   = note: alternatively, switch to llvm_asm! to keep your code working as it is

warning: use of deprecated function `time::precise_time_ns`: Use `OffsetDateTime::now() - OffsetDateTime::unix_epoch()` to get a `Duration` since a known epoch.
  --> test/delay-test/src/main.rs:85:29
   |
85 |             let mut start = time::precise_time_ns() as f64 / CONVERSION_FACTOR;
   |                             ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated function `time::precise_time_ns`: Use `OffsetDateTime::now() - OffsetDateTime::unix_epoch()` to get a `Duration` since a known epoch.
  --> test/delay-test/src/main.rs:90:27
   |
90 |                 let now = time::precise_time_ns() as f64 / CONVERSION_FACTOR;
   |                           ^^^^^^^^^^^^^^^^^^^^^

error[E0593]: closure is expected to take 4 arguments, but it takes 2 arguments
  --> test/delay-test/src/main.rs:70:45
   |
70 |                   context.add_pipeline_to_run(Arc::new(
   |  _____________________________________________^
71 | |                     move |p, s: &mut StandaloneScheduler| test(p, s, delay),
   | |                     ------------------------------------- takes 2 arguments
72 | |                 ));
   | |_________________^ expected closure that takes 4 arguments

error: aborting due to 2 previous errors; 2 warnings emitted

For more information about this error, try `rustc --explain E0593`.
error: could not compile `zcsi-delay`

i don't know how to fix it, plz help :) 
or should i run splinter in cloudlab?  I don't know how to get a account  of cloudlab.

**Comment by ankitbhrdwj** [comment]
@742362144 Both [NetBricks](https://github.com/NetSys/NetBricks) and Splinter are implemented using Rust nightly, and the syntax for nightly changes almost every week. However, I updated the code recently to run with the latest rust-nightly, so it should work. 

Splinter does not use the code which you are trying to compile, so I did not update that part. Run [setup.sh](https://github.com/utah-scs/splinter/blob/master/setup.sh) to compile the Netbricks code, and run `make` after that.

Setup script does not install dependencies needed for NIC(for DPDK), depending on the NIC manufacturer (Intel or Mellanox)setup the environment.

Cloudlab account is not needed if you have two servers with DPDK compatible NICs.

**Comment by 742362144** [comment]
> @742362144 Both [NetBricks](https://github.com/NetSys/NetBricks) and Splinter are implemented using Rust nightly, and the syntax for nightly changes almost every week. However, I updated the code recently to run with the latest rust-nightly, so it should work.
> 
> Splinter does not use the code which you are trying to compile, so I did not update that part. Run [setup.sh](https://github.com/utah-scs/splinter/blob/master/setup.sh) to compile the Netbricks code, and run `make` after that.
> 
> Setup script does not install dependencies needed for NIC(for DPDK), depending on the NIC manufacturer (Intel or Mellanox)setup the environment.
> 
> Cloudlab account is not needed if you have two servers with DPDK compatible NICs.
